name: Publish Docker and Kubernetes News

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fetch latest news
        run: python scripts/fetch_news.py
        
      - name: Generate blog posts
        run: python scripts/generate_posts.py
        
      - name: Publish to WordPress
        run: python scripts/publish_to_wordpress.py
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          WP_API_URL: ${{ secrets.WP_API_URL }}
          
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update content $(date +'%Y-%m-%d %H:%M:%S')"
          git push
